# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cce9857149574dc88e4479711cf884c6e252429af3f926a38d8123faf74c39ef47c7f3da1be1fe35a824ad714f2e4b5a62c10914e91fd91b02f1709d22b1d89

test:
  secret_key_base: 87f6f6c7652c74a805e75345d69bb45d0aee8af782f9691482c2bd540b4dcf8287ad55e6d1ed5082d8e753bf5bfa3de0cb70ed29613ad76b84ffe17fb70bade1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
